In [21]:
import pandas as pd

In [22]:
train = pd.read_parquet('train_best.parquet')

In [23]:
test = pd.read_parquet('test_best.parquet')

In [24]:
train_cor = train.copy()
test_cor = test.copy()

In [25]:
train

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,label,chol_count,trestbps_count,cp_count
0,0.469388,1.0,1.0,2,2,0.0,2.0,0.457746,1.0,0.454545,0.0,1.0,1.0,0.0,230,211,44
1,0.530612,1.0,3.0,2,2,0.0,0.0,0.633803,1.0,0.465909,1.0,0.0,3.0,2.0,230,211,204
2,0.714286,1.0,4.0,3,0,0.0,2.0,0.626761,0.0,0.522727,0.0,0.0,0.0,2.0,201,485,495
3,0.489796,0.0,2.0,3,0,0.0,0.0,0.563380,0.0,0.295455,1.0,0.0,0.0,0.0,201,485,173
4,0.551020,1.0,4.0,3,2,0.0,0.0,0.359155,1.0,0.931818,2.0,0.0,3.0,3.0,230,485,495
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,0.367347,1.0,3.0,2,2,0.0,0.0,0.633803,0.0,0.295455,1.0,0.0,0.0,0.0,230,211,204
728,0.693878,1.0,3.0,0,2,0.0,1.0,0.546008,0.0,0.394986,1.0,0.0,0.0,1.0,230,59,204
729,0.306122,0.0,3.0,2,2,0.0,0.0,0.739437,0.0,0.318182,1.0,0.0,1.0,0.0,230,211,204
730,0.816327,1.0,3.0,3,1,1.0,0.0,0.507042,0.0,0.295455,1.0,0.0,2.0,1.0,128,485,204
731,0.265306,0.0,2.0,2,3,0.0,0.0,0.725352,0.0,0.295455,0.0,0.0,1.0,0.0,357,211,173

In [26]:
test

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,label,chol_count,trestbps_count,cp_count
732,0.591837,1.0,4.0,3,1,0.0,2.0,0.415493,1.0,0.636364,2.0,0.0,0.0,0.0,128,485,495
733,0.489796,1.0,2.0,3,1,0.0,0.0,0.739437,0.0,0.295455,1.0,0.0,0.0,0.0,128,485,173
734,0.408163,1.0,2.0,1,0,0.0,0.0,0.281690,0.0,0.295455,1.0,0.0,0.0,0.0,201,161,173
735,0.693878,1.0,4.0,1,0,0.0,0.0,0.478873,1.0,0.579545,2.0,0.0,0.0,0.0,201,161,495
736,0.469388,1.0,3.0,1,1,0.0,0.0,0.443662,0.0,0.363636,0.0,0.0,1.0,0.0,128,161,204
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,0.530612,1.0,4.0,3,1,0.0,0.0,0.577465,1.0,0.522727,1.0,0.0,0.0,0.0,128,485,495
912,0.551020,1.0,2.0,1,2,1.0,1.0,0.845070,0.0,0.394986,1.0,0.0,0.0,0.0,230,161,173
913,0.795918,1.0,3.0,3,2,0.0,2.0,0.633803,0.0,0.386364,1.0,0.0,3.0,0.0,230,485,204
914,0.632653,1.0,1.0,3,3,0.0,2.0,0.697183,0.0,0.318182,1.0,0.0,3.0,0.0,357,485,44
915,0.612245,1.0,4.0,0,2,1.0,0.0,0.546008,0.0,0.394986,1.0,0.0,0.0,0.0,230,59,495

In [27]:
import pandas as pd
from sklearn.linear_model import LogisticRegression

# Suponiendo que df es tu DataFrame
X = train.drop('label', axis=1)  # Features
y = train['label']  # Variable dependiente

# Crear y entrenar el modelo de regresiÃ³n logÃ­stica multinomial
model = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=1000)
model.fit(X, y)

# Obtener los coeficientes de cada variable
coeficients = model.coef_
intercept = model.intercept_

# Imprimir los coeficientes de las variables
coeficients_df = pd.DataFrame(coeficients, columns=X.columns)
intercept_df = pd.DataFrame(intercept, columns=['intercept'])
result_df = pd.concat([intercept_df, coeficients_df], axis=1)
print("Coeficients:")
print(result_df)

Coeficients:
   intercept       age       sex        cp  trestbps      chol       fbs  \
0   2.141051 -0.256329 -1.185958  0.697236  0.901957  0.655044 -0.682075
1  -0.007799  0.066927  0.144846  0.407732  0.258822 -0.124447 -0.207241
2  -0.775707  0.041975  0.495527 -0.466750 -0.325042 -0.361846  0.424393
3  -0.692529  0.441104  0.574585 -0.137675 -0.512859 -0.286646  0.644347
4  -0.665016 -0.293678 -0.028999 -0.500543 -0.322877  0.117895 -0.179424

    restecg   thalach     exang   oldpeak     slope        ca      thal  \
0  0.049984  2.045489 -1.169441 -0.630291 -0.622492 -0.743214 -0.297118
1 -0.081434  0.410636 -0.101181 -0.534614 -0.238439 -0.146576  0.168129
2 -0.101535 -0.511431  0.184024  0.124311  0.246215  0.333731  0.119334
3 -0.008936 -1.290023  0.657356  0.516211  0.025614  0.389796  0.108637
4  0.141922 -0.654671  0.429242  0.524383  0.589101  0.166263 -0.098983

   chol_count  trestbps_count  cp_count
0   -0.005303       -0.003877 -0.006628
1    0.001316       -0.002855 -0.001345
2    0.002918        0.002618  0.003707
3    0.002555        0.002630  0.000865
4   -0.001486        0.001484  0.003401

/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [28]:
result_df

,intercept,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,chol_count,trestbps_count,cp_count
0,2.141051,-0.256329,-1.185958,0.697236,0.901957,0.655044,-0.682075,0.049984,2.045489,-1.169441,-0.630291,-0.622492,-0.743214,-0.297118,-0.005303,-0.003877,-0.006628
1,-0.007799,0.066927,0.144846,0.407732,0.258822,-0.124447,-0.207241,-0.081434,0.410636,-0.101181,-0.534614,-0.238439,-0.146576,0.168129,0.001316,-0.002855,-0.001345
2,-0.775707,0.041975,0.495527,-0.466750,-0.325042,-0.361846,0.424393,-0.101535,-0.511431,0.184024,0.124311,0.246215,0.333731,0.119334,0.002918,0.002618,0.003707
3,-0.692529,0.441104,0.574585,-0.137675,-0.512859,-0.286646,0.644347,-0.008936,-1.290023,0.657356,0.516211,0.025614,0.389796,0.108637,0.002555,0.002630,0.000865
4,-0.665016,-0.293678,-0.028999,-0.500543,-0.322877,0.117895,-0.179424,0.141922,-0.654671,0.429242,0.524383,0.589101,0.166263,-0.098983,-0.001486,0.001484,0.003401

In [29]:
# Calcular la matriz de correlaciÃ³n
correlation_matrix = train.corr()

# Imprimir la matriz de correlaciÃ³n
print("Matriz de correlaciÃ³n:")
print(correlation_matrix)

Matriz de correlaciÃ³n:
                     age       sex        cp  trestbps      chol       fbs  \
age             1.000000  0.033218  0.159386  0.065637 -0.070192  0.217130
sex             0.033218  1.000000  0.183439 -0.070421 -0.149243  0.051794
cp              0.159386  0.183439  1.000000  0.010514 -0.092671  0.020563
trestbps        0.065637 -0.070421  0.010514  1.000000  0.068340  0.015883
chol           -0.070192 -0.149243 -0.092671  0.068340  1.000000  0.102774
fbs             0.217130  0.051794  0.020563  0.015883  0.102774  1.000000
restecg         0.179969 -0.030164  0.017989  0.029400  0.150528  0.139630
thalach        -0.335517 -0.163599 -0.363749 -0.049028  0.215342 -0.007048
exang           0.136198  0.139108  0.404778  0.185115  0.001251 -0.013409
oldpeak         0.238962  0.126931  0.227261  0.103180  0.067378  0.045502
slope           0.057751  0.093432  0.106941 -0.016375 -0.013458  0.055745
ca              0.222983 -0.047671  0.055605  0.076721  0.180698  0.101233
thal            0.148267  0.056308  0.144028  0.132854 -0.021495  0.042749
label           0.264917  0.270454  0.397885  0.027671 -0.111884  0.118242
chol_count      0.035211 -0.096257 -0.003971  0.043277  0.832461  0.095806
trestbps_count  0.112484 -0.060029  0.027779  0.945186  0.060317  0.045830
cp_count        0.143499  0.181501  0.939517  0.026128 -0.069727  0.013040

                 restecg   thalach     exang   oldpeak     slope        ca  \
age             0.179969 -0.335517  0.136198  0.238962  0.057751  0.222983
sex            -0.030164 -0.163599  0.139108  0.126931  0.093432 -0.047671
cp              0.017989 -0.363749  0.404778  0.227261  0.106941  0.055605
trestbps        0.029400 -0.049028  0.185115  0.103180 -0.016375  0.076721
chol            0.150528  0.215342  0.001251  0.067378 -0.013458  0.180698
fbs             0.139630 -0.007048 -0.013409  0.045502  0.055745  0.101233
restecg         1.000000  0.071184 -0.007979  0.107498 -0.049637  0.246725
thalach         0.071184  1.000000 -0.332055 -0.152220 -0.298008  0.024575
exang          -0.007979 -0.332055  1.000000  0.384450  0.195436  0.032584
oldpeak         0.107498 -0.152220  0.384450  1.000000  0.277396  0.199203
slope          -0.049637 -0.298008  0.195436  0.277396  1.000000 -0.104009
ca              0.246725  0.024575  0.032584  0.199203 -0.104009  1.000000
thal            0.185636  0.001691  0.173617  0.139714 -0.094210  0.353483
label           0.049529 -0.393146  0.392684  0.463051  0.238338  0.178137
chol_count      0.135987  0.075087  0.063069  0.071989  0.000584  0.131857
trestbps_count  0.044786 -0.058109  0.168577  0.113434 -0.008318  0.070221
cp_count        0.006095 -0.380609  0.425967  0.237748  0.123716  0.059719

                    thal     label  chol_count  trestbps_count  cp_count
age             0.148267  0.264917    0.035211        0.112484  0.143499
sex             0.056308  0.270454   -0.096257       -0.060029  0.181501
cp              0.144028  0.397885   -0.003971        0.027779  0.939517
trestbps        0.132854  0.027671    0.043277        0.945186  0.026128
chol           -0.021495 -0.111884    0.832461        0.060317 -0.069727
fbs             0.042749  0.118242    0.095806        0.045830  0.013040
restecg         0.185636  0.049529    0.135987        0.044786  0.006095
thalach         0.001691 -0.393146    0.075087       -0.058109 -0.380609
exang           0.173617  0.392684    0.063069        0.168577  0.425967
oldpeak         0.139714  0.463051    0.071989        0.113434  0.237748
slope          -0.094210  0.238338    0.000584       -0.008318  0.123716
ca              0.353483  0.178137    0.131857        0.070221  0.059719
thal            1.000000  0.166704   -0.015268        0.100206  0.137585
label           0.166704  1.000000    0.017718        0.053018  0.409541
chol_count     -0.015268  0.017718    1.000000        0.037475  0.020069
trestbps_count  0.100206  0.053018    0.037475        1.000000  0.034994
cp_count        0.137585  0.409541    0.020069        0.034994  1.000000

In [30]:
correlation_matrix['label']

age               0.264917
sex               0.270454
cp                0.397885
trestbps          0.027671
chol             -0.111884
fbs               0.118242
restecg           0.049529
thalach          -0.393146
exang             0.392684
oldpeak           0.463051
slope             0.238338
ca                0.178137
thal              0.166704
label             1.000000
chol_count        0.017718
trestbps_count    0.053018
cp_count          0.409541
Name: label, dtype: float64

In [31]:
dict_cor = correlation_matrix['label'].to_dict()

In [32]:
dict_cor

{'age': 0.2649170219633983,
 'sex': 0.2704539116038596,
 'cp': 0.3978852509745225,
 'trestbps': 0.027670541931687692,
 'chol': -0.11188375386086119,
 'fbs': 0.11824152578805229,
 'restecg': 0.04952921496207338,
 'thalach': -0.3931462263510609,
 'exang': 0.392684372759667,
 'oldpeak': 0.4630506046567497,
 'slope': 0.23833783784196677,
 'ca': 0.17813742037599922,
 'thal': 0.16670432150272335,
 'label': 1.0,
 'chol_count': 0.01771787892365764,
 'trestbps_count': 0.053018151247949744,
 'cp_count': 0.4095410574274274}

In [33]:
for index, row in train_cor.iterrows():
    score = 0.0
    for col in train_cor.columns[:-1]:
        if col in dict_cor: 
            if row[col] == 1:
                score += dict_cor[col] 
    train_cor.at[index, 'score_by_correlation'] = score

In [34]:
train_cor

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,label,chol_count,trestbps_count,cp_count,score_by_correlation
0,0.469388,1.0,1.0,2,2,0.0,2.0,0.457746,1.0,0.454545,0.0,1.0,1.0,0.0,230,211,44,1.405865
1,0.530612,1.0,3.0,2,2,0.0,0.0,0.633803,1.0,0.465909,1.0,0.0,3.0,2.0,230,211,204,0.901476
2,0.714286,1.0,4.0,3,0,0.0,2.0,0.626761,0.0,0.522727,0.0,0.0,0.0,2.0,201,485,495,0.270454
3,0.489796,0.0,2.0,3,0,0.0,0.0,0.563380,0.0,0.295455,1.0,0.0,0.0,0.0,201,485,173,0.238338
4,0.551020,1.0,4.0,3,2,0.0,0.0,0.359155,1.0,0.931818,2.0,0.0,3.0,3.0,230,485,495,0.663138
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
727,0.367347,1.0,3.0,2,2,0.0,0.0,0.633803,0.0,0.295455,1.0,0.0,0.0,0.0,230,211,204,0.508792
728,0.693878,1.0,3.0,0,2,0.0,1.0,0.546008,0.0,0.394986,1.0,0.0,0.0,1.0,230,59,204,1.558321
729,0.306122,0.0,3.0,2,2,0.0,0.0,0.739437,0.0,0.318182,1.0,0.0,1.0,0.0,230,211,204,0.405042
730,0.816327,1.0,3.0,3,1,1.0,0.0,0.507042,0.0,0.295455,1.0,0.0,2.0,1.0,128,485,204,1.515150
731,0.265306,0.0,2.0,2,3,0.0,0.0,0.725352,0.0,0.295455,0.0,0.0,1.0,0.0,357,211,173,0.166704

In [35]:
for index, row in test_cor.iterrows():
    score = 0.0  
    for col in test_cor.columns[:-1]:  
        if col in dict_cor: 
            if row[col] == 1: 
                score += dict_cor[col]  
    test_cor.at[index, 'score_by_correlation'] = score

In [36]:
test_cor

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,label,chol_count,trestbps_count,cp_count,score_by_correlation
732,0.591837,1.0,4.0,3,1,0.0,2.0,0.415493,1.0,0.636364,2.0,0.0,0.0,0.0,128,485,495,0.551255
733,0.489796,1.0,2.0,3,1,0.0,0.0,0.739437,0.0,0.295455,1.0,0.0,0.0,0.0,128,485,173,0.396908
734,0.408163,1.0,2.0,1,0,0.0,0.0,0.281690,0.0,0.295455,1.0,0.0,0.0,0.0,201,161,173,0.536462
735,0.693878,1.0,4.0,1,0,0.0,0.0,0.478873,1.0,0.579545,2.0,0.0,0.0,0.0,201,161,495,0.690809
736,0.469388,1.0,3.0,1,1,0.0,0.0,0.443662,0.0,0.363636,0.0,0.0,1.0,0.0,128,161,204,0.352945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911,0.530612,1.0,4.0,3,1,0.0,0.0,0.577465,1.0,0.522727,1.0,0.0,0.0,0.0,128,485,495,0.789592
912,0.551020,1.0,2.0,1,2,1.0,1.0,0.845070,0.0,0.394986,1.0,0.0,0.0,0.0,230,161,173,0.704233
913,0.795918,1.0,3.0,3,2,0.0,2.0,0.633803,0.0,0.386364,1.0,0.0,3.0,0.0,230,485,204,0.508792
914,0.632653,1.0,1.0,3,3,0.0,2.0,0.697183,0.0,0.318182,1.0,0.0,3.0,0.0,357,485,44,0.906677
915,0.612245,1.0,4.0,0,2,1.0,0.0,0.546008,0.0,0.394986,1.0,0.0,0.0,0.0,230,59,495,0.627033

In [37]:
from sklearn.model_selection import train_test_split

X4 = train_cor.drop('label', axis=1)  # Todas las columnas excepto la columna objetivo
Y4 = train_cor['label']

# Dividimos el conjunto de entrenamiento en nuevo entrenamiento y validaciÃ³n (85% entrenamiento, 15% validaciÃ³n del conjunto de entrenamiento original)
X4_train, X4_val, Y4_train, Y4_val = train_test_split(X4, Y4, test_size=0.125, random_state=42)

In [38]:
from catboost import CatBoostClassifier

best_hyperparams = {'depth': 8, 'iterations': 30, 'l2_leaf_reg': 1, 'learning_rate': 0.01}
best_cb_model = CatBoostClassifier(**best_hyperparams)
best_cb_model.fit(X4_train, Y4_train, verbose=False)

feature_importances = best_cb_model.get_feature_importance()
feature_names = X4_train.columns

importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': feature_importances})

importance_df = importance_df.sort_values(by='Importance', ascending=False)


test_end4_sin_label = test_cor.drop('label', axis=1)
predicciones4 = best_cb_model.predict(test_end4_sin_label)
probabilidades4 = best_cb_model.predict_proba(test_end4_sin_label)

predicted_df4 = test_cor.copy()
predicted_df4['label'] = predicciones4

print(predicted_df4.head())

          age  sex   cp  trestbps  chol  fbs  restecg   thalach  exang  \
732  0.591837  1.0  4.0         3     1  0.0      2.0  0.415493    1.0
733  0.489796  1.0  2.0         3     1  0.0      0.0  0.739437    0.0
734  0.408163  1.0  2.0         1     0  0.0      0.0  0.281690    0.0
735  0.693878  1.0  4.0         1     0  0.0      0.0  0.478873    1.0
736  0.469388  1.0  3.0         1     1  0.0      0.0  0.443662    0.0

      oldpeak  slope   ca  thal  label  chol_count  trestbps_count  cp_count  \
732  0.636364    2.0  0.0   0.0    2.0         128             485       495
733  0.295455    1.0  0.0   0.0    0.0         128             485       173
734  0.295455    1.0  0.0   0.0    0.0         201             161       173
735  0.579545    2.0  0.0   0.0    2.0         201             161       495
736  0.363636    0.0  0.0   1.0    0.0         128             161       204

     score_by_correlation
732              0.551255
733              0.396908
734              0.536462
735              0.690809
736              0.352945

In [40]:
# Restablecer el Ã­ndice de predicted_df para que comience en 0 y luego sumar 1 para comenzar desde 1
predicted_df4.reset_index(drop=True, inplace=True)
predicted_df4['ID'] = predicted_df4.index 

# Seleccionar las columnas 'ID' y 'label' para el nuevo DataFrame df_randomf
df_randomf3 = predicted_df4[['ID', 'label']]

# Guardar df_randomf en un archivo CSV sin el Ã­ndice de pandas
df_randomf3.to_csv('try69_data.csv', index=False)

In [41]:
paco = pd.read_csv('try56best_data.csv')

In [42]:
paco.value_counts('label')

label
0.0    106
1.0     45
2.0     24
3.0      9
dtype: int64

In [39]:
predicted_df4.value_counts('label')

label
0.0    120
2.0     41
3.0     19
1.0      4
dtype: int64